#!/usr/bin/env python3
"""Export every algorithm's effective hyperparameters as a LaTeX table.

The manuscript reports results for 26 algorithm families; the settings behind
them belong in the supplementary material so a reader can tell which numbers
come from a shared configuration and which from a library default.

Usage: export_hyperparams.py <out.tex>
"""
import sys, json, glob, os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

SHARED = ['learning_rate', 'batch_size', 'gamma', 'net_arch']
OFFP = ['buffer_size', 'learning_starts', 'train_freq', 'gradient_steps', 'tau',
        'ent_coef', 'action_noise']
ONP = ['n_steps', 'n_epochs', 'gae_lambda', 'clip_range', 'target_kl']

def collect_sb3():
    """Effective settings per SB3 family, read back from a trained run."""
    out = {}
    for f in sorted(glob.glob(str(ROOT / 'models_*/*/run_meta.json'))):
        try:
            m = json.load(open(f))
            if m.get('total_timesteps') != 150000:
                continue
            a = m.get('algo', 'SAC').upper()
            if '_h5_' in f:
                a += '+MEM'
            out.setdefault(a, m.get('hyperparams', {}))
        except Exception:
            pass
    return out

def collect_omnisafe():
    """Dual-update settings actually used by each constrained family."""
    out = {}
    for d in sorted(glob.glob(str(ROOT / 'models_cmdp/*/seed-*/'))):
        try:
            c = json.load(open(os.path.join(d, 'config.json')))
            a = c['algo']
            if a in out:
                continue
            lag = c.get('lagrange_cfgs', {})
            alg = c.get('algo_cfgs', {})
            out[a] = {k: v for k, v in
                      (('lambda_lr', lag.get('lambda_lr')),
                       ('pid_kp', lag.get('pid_kp')),
                       ('pid_ki', lag.get('pid_ki')),
                       ('pid_kd', lag.get('pid_kd')),
                       ('multiplier_init', lag.get('lagrangian_multiplier_init')),
                       ('steps_per_epoch', alg.get('steps_per_epoch')),
                       ('warmup_epochs', alg.get('warmup_epochs')))
                      if v is not None}
        except Exception:
            pass
    return out

def fmt(v):
    if v is None:
        return '---'
    if isinstance(v, float):
        return f'{v:g}'
    s = str(v).replace('_', r'\_')
    return s if len(s) < 26 else s[:23] + r'\ldots'

def main(out_path):
    sb3, om = collect_sb3(), collect_omnisafe()
    L = [r'% Auto-generated by scripts/export_hyperparams.py -- do not edit by hand.',
         r'\begin{table*}[t]', r'\centering',
         r'\caption{Effective hyperparameters. Values shared across families were',
         r'fixed so that differences between families cannot be attributed to',
         r'unequal tuning; values left at a library default are marked. Trained for',
         r'150k environment steps in every case.}',
         r'\label{tab:hyper}', r'\begin{tabular}{llr}', r'\toprule',
         r'Family & Parameter & Value \\', r'\midrule']
    for a in sorted(sb3):
        hp = sb3[a]
        keys = [k for k in SHARED + OFFP + ONP if k in hp]
        for i, k in enumerate(keys):
            fam = a.replace('_', r'\_') if i == 0 else ''
            L.append(f"{fam} & {k.replace('_', chr(92)+'_')} & {fmt(hp[k])} \\\\")
        L.append(r'\addlinespace')
    L += [r'\midrule',
          r'\multicolumn{3}{l}{\emph{Constrained families: dual-update settings}} \\',
          r'\midrule']
    for a in sorted(om):
        for i, (k, v) in enumerate(om[a].items()):
            fam = a if i == 0 else ''
            L.append(f"{fam} & {k.replace('_', chr(92)+'_')} & {fmt(v)} \\\\")
        L.append(r'\addlinespace')
    L += [r'\bottomrule', r'\end{tabular}', r'\end{table*}']
    Path(out_path).write_text('\n'.join(L) + '\n')
    print(f'{len(sb3)} SB3 families, {len(om)} constrained families -> {out_path}')

if __name__ == '__main__':
    main(sys.argv[1])
